### ISSUE TITLE
Dev Dependencies are not updated

### ISSUE THREAD

**Issue by ncatelli** [semantic-release-cargo/semantic-release-cargo#367]
Currently semantic-release-cargo will update all `build-dependencies` for a crate but will ignore `dev-dependencies`. 

```toml
[build-dependences]
some_example = { version="1.0.0" }

[dev-dependences]
some_example = { version="1.0.0" }
```

after a `semantic-release-cargo prepare 1.1.0` will yield

```toml
[build-dependences]
some_example = { version="1.1.0" }

[dev-dependences]
some_example = { version="1.0.0" }
```

 I assume this behavior is due to the dev-dependencies not factoring into publication constraints but this could lead to issues where a subcrate is used as a dev-dependency within a workspace. To prevent issues, I think either:

1. dev-dependencies should be checked in the prepare stage for version update eligibility.
2. A call out to prefer path deps over versions in the situation should be documented.
